### ISSUE TITLE
Put lacks id

### ISSUE THREAD

**Issue by juliecoding** [DevMountain/react-3-mini#6]
The onClick function on the Increase/Decrease [buttons](https://github.com/DevMountain/http-mini/blob/master/src/App.js#L130) needs to pass `v.id`. Otherwise the [put](https://github.com/DevMountain/http-mini/blob/master/src/App.js#L59) won't work.

**Comment by devlemire** [comment]
I will keep an eye out for this during the standardization process.

**Comment by devlemire** [comment]
I had no issues and `updatePrice` already was capturing an ID.
